packageExtensions:
  '@apollo/react-testing@*':
    dependencies:
      apollo-cache: '*'
      apollo-link: '*'
      apollo-client: '*'
      apollo-cache-inmemory: '*'
      graphql: '*'
      '@types/react': '*'
  '@atlantis-lab/react-locale@*':
    dependencies:
      '@types/react': '*'
  '@apollo/react-hooks@*':
    dependencies:
      apollo-cache: '*'
      apollo-link: '*'
      apollo-client: '*'
      apollo-cache-inmemory: '*'
      graphql: '*'
      '@types/react': '*'
      '@types/zen-observable': '*'
  '@atlantis-lab/next-document-with-helmet@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atlantis-lab/next-document-with-emotion@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atlantis-lab/next-app-with-apollo@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atlantis-lab/next-app-with-user@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atlantis-lab/next-app-with-provider@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atlantis-lab/next-app-with-intl@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atlantis-lab/next-app-with-helmet@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atlantis-lab/next-app-with-emotion@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atlantis-lab/next-app-with-auth@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@monstrs/nestjs-bus@*':
    dependencies:
      '@nestjs/core': '*'
  '@monstrs/nestjs-dataloader@*':
    dependencies:
      '@nestjs/core': '*'
  '@nestjs/common@*':
    dependencies:
      rxjs: '*'
      '@types/node': '*'
  '@nestjs/graphql@*':
    dependencies:
      '@nestjs/common': '*'
      apollo-server-core: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@nestjs/core': '*'
      '@nestjs/common': '*'
      rxjs: '*'
      '@types/node': '*'
  '@nestjs/terminus@*':
    dependencies:
      axios: '*'
  '@nestjs/typeorm@*':
    dependencies:
      rxjs: '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/core': '*'
      '@nestjs/common': '*'
  '@node-ts/bus-core@*':
    dependencies:
      '@node-ts/logger-core': '*'
      inversify: '*'
  '@node-ts/ddd@*':
    dependencies:
      '@node-ts/logger-core': '*'
      '@node-ts/bus-core': '*'
  '@node-ts/logger-core@*':
    dependencies:
      inversify: '*'
  '@storybook/api@*':
    dependencies:
      '@reach/router': '*'
  '@storybook/addon-knobs@*':
    dependencies:
      '@emotion/core': '*'
  '@storybook/react@*':
    dependencies:
      '@types/node': '*'
      '@types/react': '*'
  '@storybook/theming@*':
    dependencies:
      '@emotion/utils': '*'
      '@emotion/serialize': '*'
  '@storybook/addons@*':
    dependencies:
      'react': '*'
      '@types/react': '*'
      '@types/node': '*'
  '@oryd/hydra-client@*':
    dependencies:
      '@types/node': '*'
  '@grpc/proto-loader@*':
    dependencies:
      '@types/node': '*'
  '@graphql-typed-document-node/core@*':
    dependencies:
      graphql: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  '@types/rc-trigger@*':
    dependencies:
      'react': '*'
      '@types/react': '*'
  '@emotion/styled@*':
    dependencies:
      '@types/react': '*'
  '@emotion/core@*':
    dependencies:
      '@types/react': '*'
  argon2@*:
    dependencies:
      '@types/node': '*'
  apollo-server-core@*:
    dependencies:
      '@types/node': '*'
  apollo-env@*:
    dependencies:
      '@types/node': '*'
  graphql-query-complexity@*:
    dependencies:
      graphql: '*'
  graphql-subscriptions@*:
    dependencies:
      '@types/node': '*'
  type-graphql@*:
    dependencies:
      graphql: '*'
  '@elastic/elasticsearch@*':
    dependencies:
      '@types/node': '*'
  subscriptions-transport-ws@*:
    dependencies:
      '@types/node': '*'
  form-data@*:
    dependencies:
      '@types/node': '*'
  create-emotion-server@*:
    dependencies:
      '@types/node': '*'
  next@*:
    dependencies:
      '@types/node': '*'
  rc-select@*:
    dependencies:
      '@types/react': '*'
  react-scrolllock@*:
    dependencies:
      '@types/react': '*'
  graphql-tag@*:
    dependencies:
      graphql: '*'
  '@testing-library/react@*':
    dependencies:
      react-dom: '*'

plugins:
  - .yarn/plugins/@atls/plugin-essentials.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: '.yarn/releases/yarn-berry.cjs'
