packageExtensions:
  '@apollo/react-testing@*':
    dependencies:
      apollo-cache: '*'
      apollo-link: '*'
      '@apollo/client': '*'
      apollo-cache-inmemory: '*'
      graphql: '*'
      '@types/react': '*'
  '@atls/react-locale@*':
    dependencies:
      '@types/react': '*'
  '@apollo/react-hooks@*':
    dependencies:
      apollo-cache: '*'
      apollo-link: '*'
      apollo-cache-inmemory: '*'
      graphql: '*'
      react: '*'
      '@types/react': '*'
      '@types/zen-observable': '*'
  '@atls/next-document-with-helmet@*':
    dependencies:
      react: '*'
      react-helmet: '*'
      next: '*'
      '@types/react': '*'
  '@atls/next-document-with-emotion@*':
    dependencies:
      react: '*'
      emotion-server: '*'
      next: '*'
      '@types/react': '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      '@apollo/react-common': '*'
      '@apollo/react-ssr': '*'
      '@types/react': '*'
      next: '*'
      react: '*'
  '@atls/next-app-with-user@*':
    dependencies:
      '@atls/react-user': '0.1.37'
      react: '*'
      '@types/react': '*'
  '@atls/next-app-with-provider@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atls/next-app-with-intl@*':
    dependencies:
      react: '*'
      react-intl: '*'
      universal-cookie: '*'
      '@types/react': '*'
  '@atls/next-app-with-helmet@*':
    dependencies:
      react: '*'
      react-helmet: '*'
      '@types/react': '*'
  '@atls/next-app-with-emotion@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@atls/next-app-with-auth@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  '@apollo/client@*':
    dependencies:
      'react-dom': '*'
  '@apollo/react-ssr@*':
    dependencies:
      react: '*'
      graphql: '*'
  '@apollo/link-error@*':
    dependencies:
      graphql: '*'
  '@monstrs/nestjs-bus@*':
    dependencies:
      '@monstrs/nestjs-logger': '*'
      '@nestjs/core': '*'
      reflect-metadata: '*'
      serialize-error: '*'
  '@monstrs/nestjs-dataloader@*':
    dependencies:
      '@nestjs/core': '*'
  '@monstrs/server-scripts@*':
    dependencies:
      cross-spawn: '*'
      '@lerna/project': '*'
      serialize-error: '*'
  emotion-server@*:
    dependencies:
      emotion: '*'
  glob-promise@*:
    dependencies:
      glob: '*'
  '@nestjs/common@*':
    dependencies:
      rxjs: '*'
      reflect-metadata: '*'
      cache-manager: '*'
      class-validator: '*'
      class-transformer: '*'
      '@types/node': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/microservices': '*'
      '@nestjs/platform-express': '*'
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
  '@nestjs/graphql@*':
    dependencies:
      '@nestjs/common': '*'
      apollo-server-core: '*'
  '@nestjs/microservices@*':
    dependencies:
      '@nestjs/core': '*'
      '@nestjs/common': '*'
      '@nestjs/websockets': '*'
      '@types/node': '*'
      amqplib: '*'
      amqp-connection-manager: '*'
      kafkajs: '*'
      nats: '*'
      mqtt: '*'
      grpc: '*'
      rxjs: '*'
      redis: '*'
      reflect-metadata: '*'
  '@nestjs/websockets@*':
    dependencies:
      rxjs: '*'
  '@nestjs/terminus@*':
    dependencies:
      axios: '*'
  '@nestjs/typeorm@*':
    dependencies:
      '@nestjs/core': '*'
      rxjs: '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/core': '*'
      '@nestjs/common': '*'
  '@node-ts/bus-core@*':
    dependencies:
      '@node-ts/logger-core': '*'
      inversify: '*'
  '@node-ts/ddd@*':
    dependencies:
      '@node-ts/logger-core': '*'
      '@node-ts/bus-core': '*'
      inversify: '*'
      tslib: '*'
  '@node-ts/logger-core@*':
    dependencies:
      tslib: '*'
      inversify: '*'
  '@storybook/api@*':
    dependencies:
      '@reach/router': '*'
  '@storybook/addon-knobs@*':
    dependencies:
      '@emotion/core': '*'
  '@storybook/react@*':
    dependencies:
      '@types/node': '*'
      '@types/react': '*'
  '@storybook/theming@*':
    dependencies:
      '@emotion/utils': '*'
      '@emotion/serialize': '*'
  '@storybook/addons@*':
    dependencies:
      'react': '*'
      '@types/react': '*'
      '@types/node': '*'
  '@oryd/hydra-client@*':
    dependencies:
      '@types/node': '*'
  '@grpc/proto-loader@*':
    dependencies:
      '@types/node': '*'
  '@graphql-typed-document-node/core@*':
    dependencies:
      graphql: '*'
  '@mapbox/node-pre-gyp@*':
    dependencies:
      aws-sdk: '*'
      mock-aws-s3: '*'
      nock: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  '@types/rc-trigger@*':
    dependencies:
      'react': '*'
      '@types/react': '*'
  '@emotion/styled@*':
    dependencies:
      '@types/react': '*'
  '@emotion/core@*':
    dependencies:
      react: '*'
      '@types/react': '*'
  argon2@*:
    dependencies:
      '@types/node': '*'
  apollo-server-core@*:
    dependencies:
      '@types/node': '*'
  apollo-env@*:
    dependencies:
      '@types/node': '*'
  component-classes@*:
    dependencies:
      indexof: '*'
  graphql-query-complexity@*:
    dependencies:
      graphql: '*'
  graphql-subscriptions@*:
    dependencies:
      '@types/node': '*'
  type-graphql@*:
    dependencies:
      graphql: '*'
      class-validator: '*'
  '@elastic/elasticsearch@*':
    dependencies:
      '@types/node': '*'
  subscriptions-transport-ws@*:
    dependencies:
      '@types/node': '*'
  form-data@*:
    dependencies:
      '@types/node': '*'
  create-emotion-server@*:
    dependencies:
      '@types/node': '*'
  create-react-class@*:
    dependencies:
      react: '*'
  mini-store@*:
    dependencies:
      react: '*'
  next@*:
    dependencies:
      '@types/node': '*'
  mqtt@*:
    dependencies:
      duplexify: '*'
  rc-align@*:
    dependencies:
      react: '*'
      react-dom: '*'
  rc-collapse@*:
    dependencies:
      react: '*'
      react-dom: '*'
  rc-select@*:
    dependencies:
      react: '*'
      react-dom: '*'
      '@types/react': '*'
  rc-trigger@*:
    dependencies:
      react: '*'
      react-dom: '*'
      '@types/react': '*'
  rc-util@*:
    dependencies:
      react: '*'
      react-dom: '*'
      '@types/react': '*'
  react-docgen-typescript-loader@*:
    dependencies:
      webpack: '*'
  react-scrolllock@*:
    dependencies:
      '@types/react': '*'
  react-apollo@*:
    dependencies:
      apollo-link: '*'
      apollo-utilities: '*'
      apollo-cache: '*'
  react-dev-utils@*:
    dependencies:
      webpack: '*'
      typescript: '*'
  graphql-tag@*:
    dependencies:
      graphql: '*'
  webpack@*:
    dependencies:
      '@types/node': '*'
  '@testing-library/react@*':
    dependencies:
      react-dom: '*'
  next-fonts@*:
    dependencies:
      webpack: '*'
  next-images@*:
    dependencies:
      webpack: '*'
  merge-graphql-schemas@*:
    dependencies:
      graphql-tag-pluck: '*'
  '@storybook/ui@*':
    dependencies:
      '@emotion/core': '*'

plugins:
  - .yarn/plugins/@atls/plugin-essentials.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: '.yarn/releases/yarn-berry.cjs'
