version: v0.5.5-alpha.1

dsn: memory

serve:
  public:
    base_url: https://kratos.serenity.local.atls.tech/
    cors:
      enabled: true
      allowed_origins:
        - 'https://accounts.serenity.local.atls.tech'
        - 'https://kratos.serenity.local.atls.tech'
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Set-Cookie
      debug: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: https://accounts.serenity.local.atls.tech/
  whitelisted_return_urls:
    - https://accounts.serenity.local.atls.tech/
    - https://kratos.serenity.local.atls.tech/

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: https://accounts.serenity.local.atls.tech/error
    settings:
      ui_url: https://accounts.serenity.local.atls.tech/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: https://accounts.serenity.local.atls.tech/recovery
    logout:
      after:
        default_browser_return_url: https://accounts.serenity.local.atls.tech/login
    login:
      ui_url: https://accounts.serenity.local.atls.tech/login
      lifespan: 10m
    registration:
      lifespan: 10m
      ui_url: https://accounts.serenity.local.atls.tech/registration
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session

session:
  cookie:
    domain: serenity.local.atls.tech

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
